# Generated by Django 5.0.4 on 2024-05-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_librarycard_isvalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarycard',
            name='collegeYear',
            field=models.CharField(max_length=200),
        ),
    ]
